sequences = {
        '26': 'GAAGAIACAA',
        '27': 'GAAGAGACAA',
        '28': 'GAAGACACAA',
        '29': 'GAAGAUACAA',
        '30': 'GAAGAAACAA',
        '31': 'UUGUCUCUUC',
        '32': 'UUGUGUCUUC',
        '33': 'UUGUAUCUUC',
        '34': 'UUGUUUCUUC',
        '35': 'UUGUIUCUUC',
        '36': 'GAAGUIACAA',
        '37': 'GAAGUGACAA',
        '38': 'UUGUCACUUC',
        '39': 'GAAGGIACAA',
        '40': 'GAAGGGACAA',
        '41': 'UUGUCCCUUC',
        '42': 'GAAGCIACAA',
        '43': 'GAAGCGACAA',
        '44': 'UUGUCGCUUC',
        '45': 'GAAGAIUCAA',
        '46': 'GAAGAGUCAA',
        '47': 'UUGACUCUUC',
        '48': 'GAAGAIGCAA',
        '49': 'GAAGAGGCAA',
        '50': 'UUGCCUCUUC',
        '51': 'GAAGAICCAA',
        '52': 'GAAGAGCCAA',
        '53': 'UUGGCUCUUC',
        '59': 'GAAAIGCG',
        '60': 'GAAAGGCG',
        '61': 'CGCCUUUC',
        '62': 'GAAGIACG',
        '63': 'GAAGGACG',
        '64': 'CGUCCUUC',
}

